# Site Settings
title: Leonardo Assis Morais
email: leoassisfisica at gmail.com
description: Leonardo Assis Morais' academic website.
baseurl: ""
url: "https://leo-am.github.io"
twitter_username: lew_morias
github_username:  Leo-am

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

languages: ["en", "pt"]
default_lang: "en"

social:
  github: https://github.com/Leo-am
  scholar: https://scholar.google.com.au/citations?user=sQk70PoAAAAJ&hl
  orcid: https://orcid.org/0000-0003-1617-979X
  lattes: http://lattes.cnpq.br/8998169276284544
